/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vistas;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import com.mycompany.controlador.ControladorDecanos;
import com.mycompany.controlador.ControladorProfesores;

/**
 *
 * @author Calavera
 */
public class VDecanos extends javax.swing.JFrame {

    /**
     * Creates new form VDecanos
     */
    private ControladorDecanos controlador;
    
    public VDecanos() {
        initComponents();
        controlador = new ControladorDecanos(this);
    }
    // Método para agregar una fila a la tabla
public void agregarFilaATabla(String nivel, String nombre, String correoPersonal, String correoInstitucional, String sueldo, String cedula, String id) {
    DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
    modelo.addRow(new Object[]{nivel, nombre, correoPersonal, correoInstitucional, sueldo, cedula, id});
}

// Getters
public String getNivel() { 
    return jTextNivel.getText(); }
public String getNombre() { 
    return jTextNombre.getText(); }
public String getCorreoPersonal() { 
    return jTextCorreoPersonal.getText(); }
public String getCorreoInstitucional() { 
    return jTextCorreoInstitucional.getText(); }
public String getSueldo() { 
    return txtSueldo.getText(); }
public String getID() { 
    return jTextID.getText(); }
public JTable getTablaDecanos() { 
    return jTable2; }
public String getCedula() {
    return jTextFieldCedula.getText();
}

public void setCedula(String cedula) {
    jTextFieldCedula.setText(cedula);
}
// Setters (opcionalmente para Buscar)
public void setNivel(String nivel) {  
    jTextNivel.setText(nivel); }
public void setNombre(String nombre) { 
    jTextNombre.setText(nombre); }
public void setCorreoPersonal(String correo) { 
    jTextCorreoPersonal.setText(correo); }
public void setCorreoInstitucional(String correo) { 
    jTextCorreoInstitucional.setText(correo); }
public void setSueldo(String sueldo) { 
    txtSueldo.setText(sueldo); }
public void setID(String id) { 
    jTextID.setText(id); }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextNivel = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextCorreoPersonal = new javax.swing.JTextField();
        jTextCorreoInstitucional = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        jTextID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2Eliminar = new javax.swing.JButton();
        jButton3Actualizar = new javax.swing.JButton();
        jButton4Buscar = new javax.swing.JButton();
        jButton5Agregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9Cedula = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        jTextField5.setText("jTextField5");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("D E C A N O S");

        jLabel2.setText("Nivel");

        jLabel4.setText("Nombre");

        jLabel5.setText("Correo Personal");

        jLabel6.setText("Correo Isntitucional");

        jLabel7.setText("Sueldo");

        jLabel8.setText("ID");

        jTextNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNivelActionPerformed(evt);
            }
        });

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jTextCorreoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCorreoPersonalActionPerformed(evt);
            }
        });

        jTextCorreoInstitucional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCorreoInstitucionalActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");

        jButton2Eliminar.setText("Eliminar");
        jButton2Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EliminarActionPerformed(evt);
            }
        });

        jButton3Actualizar.setText("Actualizar");
        jButton3Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActualizarActionPerformed(evt);
            }
        });

        jButton4Buscar.setText("Buscar");
        jButton4Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4BuscarActionPerformed(evt);
            }
        });

        jButton5Agregar.setText("Agregar");
        jButton5Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5AgregarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nivel", "Nombre", "Correo Personal", "Correo Institucional", "Sueldo", "Cedula", "ID"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel9Cedula.setText("Cedula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton2Eliminar)
                .addGap(18, 18, 18)
                .addComponent(jButton3Actualizar)
                .addGap(18, 18, 18)
                .addComponent(jButton4Buscar)
                .addGap(18, 18, 18)
                .addComponent(jButton5Agregar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9Cedula)
                                .addGap(68, 68, 68)))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(57, 57, 57))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextID, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(txtSueldo)
                                    .addComponent(jTextCorreoInstitucional)
                                    .addComponent(jTextCorreoPersonal)
                                    .addComponent(jTextNombre)
                                    .addComponent(jTextNivel)
                                    .addComponent(jTextFieldCedula))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextCorreoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextCorreoInstitucional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9Cedula)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2Eliminar)
                    .addComponent(jButton3Actualizar)
                    .addComponent(jButton4Buscar)
                    .addComponent(jButton5Agregar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCorreoInstitucionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCorreoInstitucionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCorreoInstitucionalActionPerformed

    private void jTextCorreoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCorreoPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCorreoPersonalActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jTextNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNivelActionPerformed

    private void jButton5AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5AgregarActionPerformed
        // TODO add your handling code here:
        controlador.agregarDecano();
    }//GEN-LAST:event_jButton5AgregarActionPerformed

    private void jButton3ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActualizarActionPerformed
        // TODO add your handling code here:
        controlador.actualizarDecano();
    }//GEN-LAST:event_jButton3ActualizarActionPerformed

    private void jButton2EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EliminarActionPerformed
        // TODO add your handling code here:
        controlador.eliminarDecano();
    }//GEN-LAST:event_jButton2EliminarActionPerformed

    private void jButton4BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4BuscarActionPerformed
        // TODO add your handling code here:
        controlador.buscarDecano();
    }//GEN-LAST:event_jButton4BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VDecanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VDecanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VDecanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VDecanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VDecanos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2Eliminar;
    private javax.swing.JButton jButton3Actualizar;
    private javax.swing.JButton jButton4Buscar;
    private javax.swing.JButton jButton5Agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9Cedula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextCorreoInstitucional;
    private javax.swing.JTextField jTextCorreoPersonal;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextNivel;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
